name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cook-backend ./backend/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cook-frontend ./cook/ 
      - name: Publish on Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cook-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cook-frontend:latest
  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Stop and Remove Existing Containers
        run: |
          docker stop cook-backend || true
          docker stop cook-frontend || true
          docker rm cook-backend || true
          docker rm cook-frontend || true
      - name: Pull Docker Images
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cook-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/cook-frontend:latest
          docker image prune -f
      - name: Run Docker Images
        run: |
          docker run -d -p 4000:4000 --name cook-backend ${{ secrets.DOCKER_USERNAME }}/cook-backend:latest
          docker run -d -p 3000:3000 --name cook-frontend ${{ secrets.DOCKER_USERNAME }}/cook-frontend:latest
