name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cook-backend ./backend/
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cook-frontend ./cook/
      - name: Publish on Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cook-backend:latest
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cook-frontend:latest
